/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0256f076-5513-4b3b-a1fb-5a401bac79e1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_zOcHHB6sK",
    "aws_user_pools_web_client_id": "1i2fjk8ol93cd8o80966a0f0rg",
    "oauth": {}
};


export default awsmobile;
